In [5]:
import pandas as pd

# Read the card dataset
card_df = pd.read_csv('card.csv')

# Display basic information
print('Dataset shape:', card_df.shape)
print('\nFirst few rows:')
card_df.head()

Dataset shape: (3553303, 10)

First few rows:

,transaction_id,customer_id,amount_cad,debit_credit,transaction_datetime,merchant_category,ecommerce_ind,country,province,city
0,CARD24110131109543,SYNID0102450742,13.35,D,2024-11-01 00:00:06,5812,1,CA,ON,NaN
1,CARD24110136178868,SYNID0105586872,6.05,D,2024-11-01 00:00:17,5968,1,NaN,NaN,other
2,CARD24110173783589,SYNID0107901560,81.40,C,2024-11-01 00:00:37,4816,0,CA,BC,NaN
3,CARD24110142566805,SYNID0107237475,3.20,D,2024-11-01 00:00:41,5814,0,CA,ON,MISSISSAUGA
4,CARD24110150346602,SYNID0109982946,356.03,D,2024-11-01 00:00:51,0,0,CA,AB,CALGARY

In [6]:
# Replace NaN/empty values in country, province, and city columns with "other"
print("Before cleaning:")
print(f"Country - Total count: {len(card_df)}, NaN count: {card_df['country'].isna().sum()}")
print(f"Province - Total count: {len(card_df)}, NaN count: {card_df['province'].isna().sum()}")
print(f"City - Total count: {len(card_df)}, NaN count: {card_df['city'].isna().sum()}")

# Fill NaN values with "other"
card_df['country'] = card_df['country'].fillna('other')
card_df['province'] = card_df['province'].fillna('other')
card_df['city'] = card_df['city'].fillna('other')

print("\nAfter cleaning:")
print(f"Country - Total count: {len(card_df)}, NaN count: {card_df['country'].isna().sum()}")
print(f"Province - Total count: {len(card_df)}, NaN count: {card_df['province'].isna().sum()}")
print(f"City - Total count: {len(card_df)}, NaN count: {card_df['city'].isna().sum()}")

print("\nSample of cleaned data:")
card_df[['country', 'province', 'city']].head(10)

Before cleaning:
Country - Total count: 3553303, NaN count: 579026
Province - Total count: 3553303, NaN count: 659384
City - Total count: 3553303, NaN count: 508785

After cleaning:
Country - Total count: 3553303, NaN count: 0
Province - Total count: 3553303, NaN count: 0
City - Total count: 3553303, NaN count: 0

Sample of cleaned data:

  country province         city
0      CA       ON        other
1   other    other        other
2      CA       BC        other
3      CA       ON  MISSISSAUGA
4      CA       AB      CALGARY
5      CA       ON        other
6      CA       BC        other
7      CA       ON        other
8      CA       BC    VANCOUVER
9      CA       BC        other

In [7]:
# Save the cleaned dataframe to Card_Cleaned.csv
card_df.to_csv('Card_Cleaned.csv', index=False)
print(f"Cleaned dataset saved to 'Card_Cleaned.csv'")
print(f"Shape: {card_df.shape}")

Cleaned dataset saved to 'Card_Cleaned.csv'
Shape: (3553303, 10)